### ISSUE TITLE
Global planner is not initialized in Turtlebot

### ISSUE THREAD

**Issue by arperon** [ros-planning/navigation_experimental#43] opened 2020-01-04 03:44 UTC
Hello my friends, 
I have a issue regarding the SBPL Lattice Planner. I'm currently using ROS Kinetic and I have installed all "navigation_experimental" packages with "git clone". Before that, I've installed the "sbpl library" with "apt-get" for ROS Kinetic. I also checked for available plugins in ROS Package System using "rospack plugins --attrib=plugin nav_core" command, witch showed the sbpl_lattice_planner listed with navfn and the other planners. Then I runned a simulation with the command "roslaunch sbpl_lattice_planner move_base_sbpl_fake_localization_2.5cm.launch" and everything worked allright. Then I tried to use the planner as a global planner for nav_core in a simulation using "turtlebot_stage". The "turtlebot_stage" launched just fine and  I used the "rqt_reconfigure" GUI to change the global planner to "SBPLLatticePlanner". When I used the "2D Nav Goal" command, the robot didn't move and the terminal showed the following message: "Global planner is not initialized". Please, does anyone knows what it could be? Thanks in advance!

**Comment by mintar** [comment] 2020-01-13 15:50
It's not that easy, unfortunately.

The `turtlebot_navigation` package is configured to use NavFn instead of SBPL. So you have to modify `turtlebot_navigation`. The global planner is defined here:

https://github.com/turtlebot/turtlebot_apps/blob/4bbafc7bfdfc5888ba03b52611bdb56d86b22967/turtlebot_navigation/launch/includes/move_base.launch.xml#L23

You basically have to replace that stuff by the proper SBPL parameters for the turtlebot. You can look at my `mir_robot` repo for inspiration:

https://github.com/dfki-ric/mir_robot/blob/bc6c4ff4f9a980ec25f2159af72295411b7d09f2/mir_navigation/launch/move_base.xml#L8-L10

https://github.com/dfki-ric/mir_robot/blob/bc6c4ff4f9a980ec25f2159af72295411b7d09f2/mir_navigation/config/sbpl_global_params.yaml

If you just want to play around with SBPL, I'd recommend going to https://github.com/dfki-ric/mir_robot and following the "Gazebo demo" instructions in the README.

I'm closing this issue, since it's not a bug in sbpl_lattice_planner. If you have further questions, I encourage you to post them to https://answers.ros.org/ . Good luck!

**Closed as completed by mintar** 2020-01-13 15:50 UTC
